# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Quiz'
  app.api_version = "16"
  app.package = 'com.zlpy.quiz'
  app.main_activity = 'HomeActivity'
  app.sub_activities = ['FormActivity']
  #app.theme = '@android:style/Theme.Holo.Light'

  app.manifest.child("application") do |application|
    application['android:theme'] = '@android:style/Theme.Holo.Light'
    application.add_child('meta-data').update('android:name' => 'com.amap.api.v2.apikey',
                                              'android:value' => 'Key Value')
    #application.children('meta-data')
  end
end