# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Quiz'
  app.api_version = "16"
  app.package = 'com.zlpy.quiz'
  app.main_activity = 'HomeActivity'
  app.sub_activities = ['CheatActivity']
  app.theme = '@android:style/Theme.Holo.Light'
end
