# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'ListThings'
  app.icon = "icon"

  app.main_activity = 'MainActivity'
  app.sub_activities += %w(BaikeActivity)
  app.permissions = 'android.permission.INTERNET'

  app.api_version = "16"
  app.target_api_version = "16"
end
