# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Weather'

  app.package = "com.zlpy.weather"
  app.permissions = [:internet]
  app.vendor_project jar: "vendor/volley-1.0.9.jar"
  app.api_version = "16"
  app.target_api_version = "16"

end
